---
- hosts: dcos_bootstrap

  tasks:
    - name: Create genconf directory
      command: rm-rf /home/centos/genconf/

     
- hosts: localhost
  tasks:
    - name: clean
      shell: echo "" > /etc/ansible/hosts

    - name: clean-2
      command: rm -f *.retry


