---
- hosts: dcos_bootstrap

  tasks:
    - name: Create genconf directory
      command: mkdir -p ~/genconf

    - name: Create configuration file
      blockinfile:
        dest: ~/genconf/config.yaml
        create: yes
        state: present
        block: |
          ---
          bootstrap_url: http://{{ansible_default_ipv4.address}}:8181
          cluster_name: 'amt'
          exhibitor_storage_backend: static
          ip_detect_filename: ~/genconf/ip-detect
          resolvers:
          - 8.8.4.4
          - 8.8.8.8
          master_list:

    - name: Add master ip to file
      lineinfile:
        dest: ~/genconf/config.yaml
        state: present
        line: "{{item}}"
        with_items:
          - groups['dcos_master'].master_ip
          
    - name: Create ip-detect script
      lineinfile: 
        dest: ~/genconf/ip-detect
        create: yes
        state: present
        line: curl http://169.254.169.254/latest/meta-data/local-ipv4




    - name: Downloading DC/OS installer
      command: curl -O https://downloads.dcos.io/dcos/EarlyAccess/dcos_generate_config.sh
    
    - name: Generate DC/OS build file
      shell: dcos_generate_config.sh
      args:
        executable: /bin/bash

    - name: Run Docker Containet
      command: docker run -d -p 8181:80 -v $PWD/genconf/serve:/usr/share/nginx/html:ro nginx
      


