---
- hosts: localhost

  tasks:
    - name: Installing Python-dev and Python-pip
      apt: name= "{{item}}" state=latest update_cache=yes
      with_items:
        - python-dev
        - python-pip
      when: ansible_distribution == "Ubuntu"

    - name: Installing Python-dev and Python-pip
      yum: name= "{{item}}" python-pip update_cache=yes state=latest
      with_items:
        - python-dev
        - python-pip
      when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat"

    - name: Install Pytz
      pip: name= "{{item}}" state=forcereinstall
      with_items: 
        - pytz
        - shade
        - python-openstackclient

    - name: Add vars to file
      blockinfile:
        create: yes
        dest: group_vars/all/key_settings
        state: present
        block: |
          ---
          ansible_user: centos
          ansible_ssh_private_key_file: dcos_key.key
          ansible_become_user: root
          ansible_become: yes
 



