---
- hosts: localhost

  tasks:
    - name: Create ip-detect script
      lineinfile: 
        dest: /home/ansible/ip-detect
        create: yes
        state: present
        line: "{{item}}"
      with_items: 
        - "#!/bin/sh"
        - echo $(ip addr show eth0 | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1)

      


